spring.application.name=carereport
server.port=8081
# データベースの中身を見るための画面（H2コンソール）を有効化
spring.h2.console.enabled=true
# データベースの名前を固定する
spring.datasource.url=jdbc:h2:mem:testdb
# 挙動確認の仮データ生成用
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.datasource.initialization-mode=always
spring.sql.init.encoding=UTF-8